version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: lautaro
      POSTGRES_PASSWORD: lautaro
      POSTGRES_DB: soma-db
